version: "3.8"

services:
  blue:
    image: ${BLUE_IMAGE}
    container_name: blue_service
    environment: 
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports: 
      - "8081:8080"

  green:
    image: ${GREEN_IMAGE}
    container_name: green_service
    environment: 
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:8080"

  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    depends_on:
      - blue
      - green
