version: "3.8"

services:
  # BLUE SERVICE
  blue:
    image: ${BLUE_IMAGE}
    container_name: blue_service
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
    ports:
      - "8081:${PORT}"
    restart: always

  # GREEN SERVICE
  green:
    image: ${GREEN_IMAGE}
    container_name: green_service
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    ports:
      - "8082:${PORT}"
    restart: always

  # NGINX PROXY (Load Balancer)
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./nginx/start-nginx.sh:/start-nginx.sh
      - nginx_logs:/var/log/nginx         
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - INACTIVE_POOL=${INACTIVE_POOL}
      - RELEASE_ID_BLUE=${RELEASE_ID_BLUE}
      - RELEASE_ID_GREEN=${RELEASE_ID_GREEN}
    command: ["/bin/sh", "/start-nginx.sh"]
    depends_on:
      - blue
      - green
    restart: always

volumes:
  nginx_logs: 


