version: "3.8"

services:
  # BLUE SERVICE (Primary)
  blue:
    build:
      context: .
      dockerfile: Dockerfile.blue
    container_name: blue_service
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=8080
    ports:
      - "8081:8080"
    restart: always

  # GREEN SERVICE (Backup)
  green:
    build:
      context: .
      dockerfile: Dockerfile.green
    container_name: green_service
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=8080
    ports:
      - "8082:8080"
    restart: always

  # NGINX PROXY (Load Balancer)
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - INACTIVE_POOL=${INACTIVE_POOL}
      - ACTIVE_SERVICE=${ACTIVE_POOL}_service
      - INACTIVE_SERVICE=${INACTIVE_POOL}_service
      - RELEASE_ID_BLUE=${RELEASE_ID_BLUE}
      - RELEASE_ID_GREEN=${RELEASE_ID_GREEN}
    command: >
      /bin/sh -c "
      if [ \"$ACTIVE_POOL\" = 'blue' ]; then
        export ACTIVE_RELEASE_ID=$RELEASE_ID_BLUE;
      else
        export ACTIVE_RELEASE_ID=$RELEASE_ID_GREEN;
      fi;
      envsubst '\$ACTIVE_SERVICE \$INACTIVE_SERVICE \$ACTIVE_POOL \$INACTIVE_POOL \$ACTIVE_RELEASE_ID'
      < /etc/nginx/templates/nginx.conf.template \
      > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "
    depends_on:
      - blue
      - green
    restart: always
