version: "3.8"

services:
  # BLUE SERVICE
  blue:
    image: ${BLUE_IMAGE}
    container_name: blue_service
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
    ports:
      - "8081:${PORT}"
    restart: always

  # GREEN SERVICE
  green:
    image: ${GREEN_IMAGE}
    container_name: green_service
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    ports:
      - "8082:${PORT}"
    restart: always

  # NGINX PROXY (Load Balancer)
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./nginx/start-nginx.sh:/start-nginx.sh
      - ./nginx/init-logs.sh:/init-logs.sh
      - ./nginx/logs:/var/log/nginx        
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - INACTIVE_POOL=${INACTIVE_POOL}
      - RELEASE_ID_BLUE=${RELEASE_ID_BLUE}
      - RELEASE_ID_GREEN=${RELEASE_ID_GREEN}
    command: ["/bin/sh", "-c", "/init-logs.sh & /start-nginx.sh"]
    depends_on:
      - blue
      - green
    restart: always

  # ALERT WATCHER
  alert_watcher:
    build: ./watcher
    container_name: alert_watcher
    volumes:
      - ./nginx/logs:/var/log/nginx        
      - ./watcher:/app
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=0.2
      - WINDOW_SIZE=30
      - POLL_INTERVAL=2
    depends_on:
      - nginx
    restart: always


