version: "3.8"

services:
  # BLUE SERVICE (Primary)
  blue:
    image: ${BLUE_IMAGE}
    container_name: blue_service
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:8080"
    restart: always

  # GREEN SERVICE (Backup)
  green:
    image: ${GREEN_IMAGE}
    container_name: green_service
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:8080"
    restart: always

  # NGINX PROXY (Load Balancer)
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - INACTIVE_POOL=${INACTIVE_POOL}
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    command: /bin/sh -c "envsubst '\$ACTIVE_POOL \$INACTIVE_POOL' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - blue
      - green
    restart: always
